name = "AutoUrban"
uuid = "1385418a-9289-5a49-ab93-843b508de4cb"
repo = "https://github.com/sisl/AutoUrban.jl"
version = "0.2.0"

[deps]
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
